version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
  cypress: cypress-io/cypress@1.26.0

jobs:
  # Download, install and cache dependencies
  Installs:
    docker:
      - image: circleci/node:14.5.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - persist_to_workspace:
          paths:
            - project
          root: ~/
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ~/project/node_modules

  # Checks
  Formatting:
    docker:
      - image: circleci/node:14.5.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Prettier formatting
          command: npm run prettify .

  Linting:
    docker:
      - image: circleci/node:14.5.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: ESLint fixes
          command: npm run lint .

  Tests:
    docker:
      - image: circleci/node:14.5.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run tests
          command: npm test -- --watchAll=false

  Test-Coverage:
    docker:
      - image: circleci/node:14.5.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run tests and generate coverage report
          command: npm run test:coverage
      - codecov/upload:
          file: './coverage/clover.xml'
          token: c3cd2ffc-bdeb-4d78-8f66-2a70cec6fe8c

  # Build and deploy
  Build-and-Deploy:
    docker:
      - image: circleci/node:14.5.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Build
          command: npm run build
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting

workflows:
  push:
    jobs:
      - cypress/run
      - Installs
      - Linting:
          requires:
            - Installs
      - Formatting:
          requires:
            - Installs
      - Tests:
          requires:
            - Installs
      - Test-Coverage:
          requires:
            - Installs
      - Build-and-Deploy:
          filters:
            branches:
              only:
                - main
                - master
          requires:
            - Installs
            - Linting
            - Formatting
            - Tests
